spring:
  application:
    name: plantory-project
#  security:
#    user:
#      name: admin
#      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/plantorydb
    username: pldbid
    password: pldbpw

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    generate-ddl: true

server:
  port: 5432